/*
 * Created on 14 Nov 2015 ( Time 15:24:18 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.cuong.futurenav.dao.dto;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "fav_school"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="fav_school", catalog="dev" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="FavSchoolEntity.countAll", query="SELECT COUNT(x) FROM FavSchoolEntity x" )
} )
public class FavSchoolEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Integer    id           ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="affiliate_type", length=36)
    private String     affiliateType ;

    @Column(name="note", length=1000)
    private String     note         ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="au_created_dt", nullable=false, updatable=false, insertable=false)
    private Date       auCreatedDt  ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="au_updated_dt", nullable=false, updatable=false, insertable=false)
    private Date       auUpdatedDt  ;

    @Column(name="au_created_by")
    private Integer    auCreatedBy  ;

    @Column(name="au_updated_by")
    private Integer    auUpdatedBy  ;

	// "studentId" (column "student_id") is not defined by itself because used as FK in a link 
	// "schoolId" (column "school_id") is not defined by itself because used as FK in a link 


    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @ManyToOne
    @JoinColumn(name="school_id", referencedColumnName="id")
    private SchoolEntity school      ;

    @ManyToOne
    @JoinColumn(name="student_id", referencedColumnName="id")
    private StudentEntity student     ;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public FavSchoolEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id ) {
        this.id = id ;
    }
    public Integer getId() {
        return this.id;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : affiliate_type ( SET ) 
    public void setAffiliateType( String affiliateType ) {
        this.affiliateType = affiliateType;
    }
    public String getAffiliateType() {
        return this.affiliateType;
    }

    //--- DATABASE MAPPING : note ( VARCHAR ) 
    public void setNote( String note ) {
        this.note = note;
    }
    public String getNote() {
        return this.note;
    }

    //--- DATABASE MAPPING : au_created_dt ( DATETIME ) 
    public void setAuCreatedDt( Date auCreatedDt ) {
        this.auCreatedDt = auCreatedDt;
    }
    public Date getAuCreatedDt() {
        return this.auCreatedDt;
    }

    //--- DATABASE MAPPING : au_updated_dt ( DATETIME ) 
    public void setAuUpdatedDt( Date auUpdatedDt ) {
        this.auUpdatedDt = auUpdatedDt;
    }
    public Date getAuUpdatedDt() {
        return this.auUpdatedDt;
    }

    //--- DATABASE MAPPING : au_created_by ( INT ) 
    public void setAuCreatedBy( Integer auCreatedBy ) {
        this.auCreatedBy = auCreatedBy;
    }
    public Integer getAuCreatedBy() {
        return this.auCreatedBy;
    }

    //--- DATABASE MAPPING : au_updated_by ( INT ) 
    public void setAuUpdatedBy( Integer auUpdatedBy ) {
        this.auUpdatedBy = auUpdatedBy;
    }
    public Integer getAuUpdatedBy() {
        return this.auUpdatedBy;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setSchool( SchoolEntity school ) {
        this.school = school;
    }
    public SchoolEntity getSchool() {
        return this.school;
    }

    public void setStudent( StudentEntity student ) {
        this.student = student;
    }
    public StudentEntity getStudent() {
        return this.student;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(id);
        sb.append("]:"); 
        sb.append(affiliateType);
        sb.append("|");
        sb.append(note);
        sb.append("|");
        sb.append(auCreatedDt);
        sb.append("|");
        sb.append(auUpdatedDt);
        sb.append("|");
        sb.append(auCreatedBy);
        sb.append("|");
        sb.append(auUpdatedBy);
        return sb.toString(); 
    } 

}
