/*
 * Created on 24 Nov 2015 ( Time 13:51:48 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.cuong.futurenav.dao.dto;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;
import java.util.List;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "student"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="student", catalog="dev2" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="StudentEntity.countAll", query="SELECT COUNT(x) FROM StudentEntity x" )
} )
public class StudentEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Integer    id           ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="name_first", length=40)
    private String     nameFirst    ;

    @Column(name="name_last", length=40)
    private String     nameLast     ;

    @Column(name="name_middle", length=40)
    private String     nameMiddle   ;

    @Column(name="name_display", nullable=false, length=40)
    private String     nameDisplay  ;

    @Column(name="email", nullable=false, length=100)
    private String     email        ;

    @Column(name="city", length=100)
    private String     city         ;

    @Column(name="country", length=100)
    private String     country      ;

    @Temporal(TemporalType.DATE)
    @Column(name="born_year")
    private Date       bornYear     ;

    @Temporal(TemporalType.DATE)
    @Column(name="birth_date")
    private Date       birthDate    ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="au_created_dt", nullable=false, updatable=false, insertable=false)
    private Date       auCreatedDt  ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="au_updated_dt", nullable=false, updatable=false, insertable=false)
    private Date       auUpdatedDt  ;

    @Column(name="au_created_by")
    private Integer    auCreatedBy  ;

    @Column(name="au_updated_by")
    private Integer    auUpdatedBy  ;

    @Column(name="networkuserid", length=100)
    private String     networkuserid ;

    @Column(name="networkgroup", length=20)
    private String     networkgroup ;

    @Column(name="photo_url", length=200)
    private String     photoUrl     ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @OneToMany(mappedBy="student", targetEntity=FavSchoolEntity.class, fetch = FetchType.EAGER)
    private List<FavSchoolEntity> listOfFavSchool;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public StudentEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id ) {
        this.id = id ;
    }
    public Integer getId() {
        return this.id;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : name_first ( VARCHAR ) 
    public void setNameFirst( String nameFirst ) {
        this.nameFirst = nameFirst;
    }
    public String getNameFirst() {
        return this.nameFirst;
    }

    //--- DATABASE MAPPING : name_last ( VARCHAR ) 
    public void setNameLast( String nameLast ) {
        this.nameLast = nameLast;
    }
    public String getNameLast() {
        return this.nameLast;
    }

    //--- DATABASE MAPPING : name_middle ( VARCHAR ) 
    public void setNameMiddle( String nameMiddle ) {
        this.nameMiddle = nameMiddle;
    }
    public String getNameMiddle() {
        return this.nameMiddle;
    }

    //--- DATABASE MAPPING : name_display ( VARCHAR ) 
    public void setNameDisplay( String nameDisplay ) {
        this.nameDisplay = nameDisplay;
    }
    public String getNameDisplay() {
        return this.nameDisplay;
    }

    //--- DATABASE MAPPING : email ( VARCHAR ) 
    public void setEmail( String email ) {
        this.email = email;
    }
    public String getEmail() {
        return this.email;
    }

    //--- DATABASE MAPPING : city ( VARCHAR ) 
    public void setCity( String city ) {
        this.city = city;
    }
    public String getCity() {
        return this.city;
    }

    //--- DATABASE MAPPING : country ( VARCHAR ) 
    public void setCountry( String country ) {
        this.country = country;
    }
    public String getCountry() {
        return this.country;
    }

    //--- DATABASE MAPPING : born_year ( YEAR ) 
    public void setBornYear( Date bornYear ) {
        this.bornYear = bornYear;
    }
    public Date getBornYear() {
        return this.bornYear;
    }

    //--- DATABASE MAPPING : birth_date ( DATE ) 
    public void setBirthDate( Date birthDate ) {
        this.birthDate = birthDate;
    }
    public Date getBirthDate() {
        return this.birthDate;
    }

    //--- DATABASE MAPPING : au_created_dt ( DATETIME ) 
    public void setAuCreatedDt( Date auCreatedDt ) {
        this.auCreatedDt = auCreatedDt;
    }
    public Date getAuCreatedDt() {
        return this.auCreatedDt;
    }

    //--- DATABASE MAPPING : au_updated_dt ( DATETIME ) 
    public void setAuUpdatedDt( Date auUpdatedDt ) {
        this.auUpdatedDt = auUpdatedDt;
    }
    public Date getAuUpdatedDt() {
        return this.auUpdatedDt;
    }

    //--- DATABASE MAPPING : au_created_by ( INT ) 
    public void setAuCreatedBy( Integer auCreatedBy ) {
        this.auCreatedBy = auCreatedBy;
    }
    public Integer getAuCreatedBy() {
        return this.auCreatedBy;
    }

    //--- DATABASE MAPPING : au_updated_by ( INT ) 
    public void setAuUpdatedBy( Integer auUpdatedBy ) {
        this.auUpdatedBy = auUpdatedBy;
    }
    public Integer getAuUpdatedBy() {
        return this.auUpdatedBy;
    }

    //--- DATABASE MAPPING : networkuserid ( VARCHAR ) 
    public void setNetworkuserid( String networkuserid ) {
        this.networkuserid = networkuserid;
    }
    public String getNetworkuserid() {
        return this.networkuserid;
    }

    //--- DATABASE MAPPING : networkgroup ( VARCHAR ) 
    public void setNetworkgroup( String networkgroup ) {
        this.networkgroup = networkgroup;
    }
    public String getNetworkgroup() {
        return this.networkgroup;
    }

    //--- DATABASE MAPPING : photo_url ( VARCHAR ) 
    public void setPhotoUrl( String photoUrl ) {
        this.photoUrl = photoUrl;
    }
    public String getPhotoUrl() {
        return this.photoUrl;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setListOfFavSchool( List<FavSchoolEntity> listOfFavSchool ) {
        this.listOfFavSchool = listOfFavSchool;
    }
    public List<FavSchoolEntity> getListOfFavSchool() {
        return this.listOfFavSchool;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(id);
        sb.append("]:"); 
        sb.append(nameFirst);
        sb.append("|");
        sb.append(nameLast);
        sb.append("|");
        sb.append(nameMiddle);
        sb.append("|");
        sb.append(nameDisplay);
        sb.append("|");
        sb.append(email);
        sb.append("|");
        sb.append(city);
        sb.append("|");
        sb.append(country);
        sb.append("|");
        sb.append(bornYear);
        sb.append("|");
        sb.append(birthDate);
        sb.append("|");
        sb.append(auCreatedDt);
        sb.append("|");
        sb.append(auUpdatedDt);
        sb.append("|");
        sb.append(auCreatedBy);
        sb.append("|");
        sb.append(auUpdatedBy);
        sb.append("|");
        sb.append(networkuserid);
        sb.append("|");
        sb.append(networkgroup);
        sb.append("|");
        sb.append(photoUrl);
        return sb.toString(); 
    } 

}
