/*
 * Created on 14 Nov 2015 ( Time 15:24:12 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.cuong.futurenav.dao.dto;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "student_login"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="student_login", catalog="dev" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="StudentLoginEntity.countAll", query="SELECT COUNT(x) FROM StudentLoginEntity x" )
} )
public class StudentLoginEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Integer    id           ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="login_name", length=40)
    private String     loginName    ;

    @Column(name="email", nullable=false, length=100)
    private String     email        ;

    @Column(name="relationship", length=19)
    private String     relationship ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="au_created_dt", nullable=false, updatable=false, insertable=false)
    private Date       auCreatedDt  ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="au_updated_dt", nullable=false, updatable=false, insertable=false)
    private Date       auUpdatedDt  ;

    @Column(name="au_created_by")
    private Integer    auCreatedBy  ;

    @Column(name="au_updated_by")
    private Integer    auUpdatedBy  ;

	// "studentId" (column "student_id") is not defined by itself because used as FK in a link 


    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @ManyToOne
    @JoinColumn(name="student_id", referencedColumnName="id")
    private StudentEntity student     ;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public StudentLoginEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id ) {
        this.id = id ;
    }
    public Integer getId() {
        return this.id;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : login_name ( VARCHAR ) 
    public void setLoginName( String loginName ) {
        this.loginName = loginName;
    }
    public String getLoginName() {
        return this.loginName;
    }

    //--- DATABASE MAPPING : email ( VARCHAR ) 
    public void setEmail( String email ) {
        this.email = email;
    }
    public String getEmail() {
        return this.email;
    }

    //--- DATABASE MAPPING : relationship ( SET ) 
    public void setRelationship( String relationship ) {
        this.relationship = relationship;
    }
    public String getRelationship() {
        return this.relationship;
    }

    //--- DATABASE MAPPING : au_created_dt ( DATETIME ) 
    public void setAuCreatedDt( Date auCreatedDt ) {
        this.auCreatedDt = auCreatedDt;
    }
    public Date getAuCreatedDt() {
        return this.auCreatedDt;
    }

    //--- DATABASE MAPPING : au_updated_dt ( DATETIME ) 
    public void setAuUpdatedDt( Date auUpdatedDt ) {
        this.auUpdatedDt = auUpdatedDt;
    }
    public Date getAuUpdatedDt() {
        return this.auUpdatedDt;
    }

    //--- DATABASE MAPPING : au_created_by ( INT ) 
    public void setAuCreatedBy( Integer auCreatedBy ) {
        this.auCreatedBy = auCreatedBy;
    }
    public Integer getAuCreatedBy() {
        return this.auCreatedBy;
    }

    //--- DATABASE MAPPING : au_updated_by ( INT ) 
    public void setAuUpdatedBy( Integer auUpdatedBy ) {
        this.auUpdatedBy = auUpdatedBy;
    }
    public Integer getAuUpdatedBy() {
        return this.auUpdatedBy;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setStudent( StudentEntity student ) {
        this.student = student;
    }
    public StudentEntity getStudent() {
        return this.student;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(id);
        sb.append("]:"); 
        sb.append(loginName);
        sb.append("|");
        sb.append(email);
        sb.append("|");
        sb.append(relationship);
        sb.append("|");
        sb.append(auCreatedDt);
        sb.append("|");
        sb.append(auUpdatedDt);
        sb.append("|");
        sb.append(auCreatedBy);
        sb.append("|");
        sb.append(auUpdatedBy);
        return sb.toString(); 
    } 

}
